embedding:
  model_name: sentence-transformers/all-roberta-large-v1
  normalize: true
  min_dimension: 1024
  api_provider: huggingface
  model_dimension: 1024
  encode_kwargs:
    normalize_embeddings: true

backend:
  chroma_dir: ./.chroma
  collection_name: code_index

indexing:
  local_repo_root: ./repos
  repo_urls:
    - 'https://github.com/Orange-Health/citadel.git'
    - 'https://github.com/Orange-Health/oms.git' 
  include_globs: ["**/*"]
  exclude_globs: ["**/.git/**","**/.github/**","**/node_modules/**","**/dist/**","**/build/**","**/*.min.js","**/*.png","**/*.jpg","**/*.jpeg","**/*.pdf"]
  max_file_mb: 1.5
  chunk_size: 1200
  chunk_overlap: 150
  batch_size: 4000
  github_token_env: GITHUB_TOKEN
  github_auth_required: true

retrieval:
  top_k: 12
  alpha_hybrid: 0.3
  use_reranker: false
  cross_encoder_model: cross-encoder/ms-marco-MiniLM-L-6-v2

server:
  host: 0.0.0.0
  port: 8000

gemini_chat_model: gemini-1.5-flash
app_env: prod
